### ISSUE TITLE
Hotkey to display current territory as a toast?

### ISSUE THREAD

**Issue by nebula161** [VastInfiniteNet/TerritoryAlerter#1]

**Comment by VastInfiniteNet** [comment]
Something I briefly considered in the beginning; i will add it.

**Comment by VastInfiniteNet** [comment]
@nebula161 I made it so: 
1. if using script as a service, you can set an optional config variable to a key name and press that to trigger a territory check
2. if using script as a keybind, if script is activated, you can press same keybind to trigger a territory check
