### ISSUE TITLE
Displaying borders ala Civilisation style

### ISSUE THREAD

**Issue by Protonull** [VastInfiniteNet/TerritoryAlerter#4]
Would it be possible to render borders somehow, similarly to how Civ5 renders borders?

![Civ5 borders](https://static.wikia.nocookie.net/civilization/images/4/44/Borders1_%28Civ5%29.jpg/revision/latest/scale-to-width-down/1000)

**Comment by VastInfiniteNet** [comment]
Funny you ask this, I was recently thinking of adding something like this.

 I'm not quite sure what it should look like. Currently have 2 thoughts:

1. To look similar to the world border; basically just a partially transparent vertical colored plane; and
2. Highlight the nearest block(s) to the player that are on the border, probably with text saying what the border is of.

I've played around with the JsMacro 2d and 3d drawing methods so I definitely think something is possible.

**Comment by Protonull** [comment]
Yeah, I did some searching and found this ([FBorder-Addon](https://github.com/Braffolk/FBorder-Addon)) which uses particles to demarcate faction borders, which is interesting and pretty, but probably not very useful for us. I think you're right that vertical panes are the way to go since you'd want to know whether you're approaching a border regardless of whether you're on the surfance, at skylimit, or deep underground.

And I think you're right about wanting to mark the border with text too, though I'm not sure how that would be done. Idealy, you wouldn't just have it directly in front of the player, but rather, perhaps, at particular intervals? Unless they're not visible, at which you would display it in-front of the player?

**Comment by VastInfiniteNet** [comment]
I think I'm going to work on a prototype of a couple  different designs (world border, single block highlight, multismall block highlight of the nearest border line). 

I think JsMacros surfaces could potentially be nice for displaying the text ( maybe I can make a fake sign of with text that rotates to always face the player?), but I havent touched surfaces yet.

I might try to mimic the FBorder-Addon particle effects too. I *might* be able to achieve something somewhat similar with surfaces via rotations and scaling. idk i'll see how it goes.

**Comment by VastInfiniteNet** [comment]
hmm seems like JsMacros added a lot to surface in recent update, but they haven't been backported to 1.18.2 yet. I want to keep this usable on 1.18.2 as that will be the major version people would be using.

**Comment by VastInfiniteNet** [comment]
Damn 1.8.4 has a bunch of new stuff, including spawning particles, but 1.8.4 isn't backported yet.

https://jsmacros.wagyourtail.xyz/?/1.8.4/xyz/wagyourtail/jsmacros/client/api/library/impl/FWorld.html#spawnParticle-String-double-double-double-double-double-double-double-int-boolean-

**Comment by VastInfiniteNet** [comment]
Revamped this project in a new repo. Made a copy of this issue in the new repo: https://github.com/VastInfiniteNet/Herm/issues/2

New project: https://github.com/VastInfiniteNet/Herm
